type: validity
description: "Validity Benchmark for Materials Generation"
version: "0.2.0"
charge_tolerance: 0.1
distance_scaling: 0.5
min_density: 0.01
max_density: 25.0
check_format: true
check_symmetry: true